# Generated by Django 4.2 on 2023-05-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NormalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField()),
                ('supplier_alligment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.normaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cashier')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.normaldocument')),
                ('id_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.partsinfo')),
            ],
        ),
    ]
